SELECT GETDATE()

SELECT YEAR(GETDATE()) 'YEAR',MONTH(GETDATE()) 'MONTH',DAY(GETDATE()) 'DAY'



SELECT DATENAME(YEAR, GETDATE()) AS YEAR,
       DATENAME(QUARTER, GETDATE()) AS QUARTER,
       DATENAME(MONTH, GETDATE()) AS MONTH,
       DATENAME(DAYOFYEAR, GETDATE()) AS DAYOFYEAR,
       DATENAME(DAY, GETDATE()) AS DAY,
       DATENAME(WEEK, GETDATE()) AS WEEK,
       DATENAME(WEEKDAY, GETDATE()) AS DAYOFWEEK,
       DATENAME(HOUR, GETDATE()) AS HOUR,
       DATENAME(MINUTE, GETDATE()) AS MINUTE,
       DATENAME(SECOND, GETDATE()) AS SECOND,
       DATENAME(MILLISECOND, GETDATE()) AS MILLISECOND,
       DATENAME(MICROSECOND, GETDATE()) AS MICROSECOND,
       DATENAME(NANOSECOND, GETDATE()) AS NANOSECOND

 