SELECT 'SQL SERVER'+NULL +'HI'
SET CONCAT_NULL_YIELDS_NULL OFF 
SELECT 'SQL SERVER'+NULL +'HI'
SET CONCAT_NULL_YIELDS_NULL ON

INSERT INTO Users VALUES ('Abc@gmail.com','ABC@1234',NULL,'M','2016-06-02','XYZ')
SELECT * FROM Users

SELECT * FROM Users where RoleId is null
SET ANSI_NULLS OFF
SELECT * FROM Users where RoleId = null
SET ANSI_NULLS ON