--CREATE PROCEDURE usp_AdditionOfNumbers

ALTER PROCEDURE usp_AdditionOfNumbers(
@NUMBER1 INT,
@NUMBER2 INT,
@RESULT INT OUT 
)WITH ENCRYPTION --WITH ENCRYPTION IS USED FOR ENCRYPTING CODE THIS WILL HIDE OUR STORED PROCEDURE
AS 
BEGIN
SET @RESULT=@NUMBER1+@NUMBER2 --TO STORE LOGIC WE USE STORED PROCEDURES WHICH IS NOT POSSIBLE IN BATCH 
PRINT @RESULT
PRINT 'THIS IS A STORED PROCEDURE'
RETURN 1
END


DECLARE @VALUE1 INT=100,@VALUE2 INT=20,@TOTAL INT,@RETURNVALUE INT 
EXEC @RETURNVALUE=usp_AdditionOfNumbers @VALUE1,@VALUE2,@TOTAL OUT WITH RECOMPILE --WITH RECOMPILE IS USED FOR EVERYTIME EXCEUTION PLANK TAKES PLACE
SELECT @TOTAL AS 'RESULT',@RETURNVALUE as 'RETURN VALUE'                            --WE CAN USE IT IN ALTER OR IN EXEC STATEMENT(WITH RECOMPILE)


--SP_HELPTEXT usp_AdditionOfNumbers
